# Generated by Django 5.0.1 on 2024-11-15 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_generalimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GeneralImage",
            new_name="frontpageImage",
        ),
        migrations.AlterModelOptions(
            name="frontpageimage",
            options={
                "ordering": ["-created"],
                "verbose_name": "首頁圖片",
                "verbose_name_plural": "首頁圖片",
            },
        ),
    ]
