# Generated by Django 5.0.1 on 2024-11-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_rename_generalimage_frontpageimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="圖片名稱")),
                (
                    "image",
                    models.ImageField(upload_to="general_images/", verbose_name="圖片"),
                ),
                (
                    "category",
                    models.CharField(
                        default="carousel", max_length=50, verbose_name="圖片分類"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="圖片描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
        ),
    ]
