# Generated by Django 5.0.1 on 2024-11-15 19:59

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_generalimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generalimage",
            options={
                "ordering": ["-created"],
                "verbose_name": "通用圖片",
                "verbose_name_plural": "通用圖片",
            },
        ),
        migrations.AddField(
            model_name="generalimage",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="修改日期"),
        ),
        migrations.AlterField(
            model_name="generalimage",
            name="category",
            field=models.CharField(
                choices=[
                    ("Nike", "Nike"),
                    ("adidas 愛迪達", "adidas 愛迪達"),
                    ("NEW BALANCE", "NEW BALANCE"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=20,
                verbose_name="圖片分類",
            ),
        ),
        migrations.AlterField(
            model_name="generalimage",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立日期"),
        ),
        migrations.AlterField(
            model_name="generalimage",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="圖片描述"
            ),
        ),
        migrations.AlterField(
            model_name="generalimage",
            name="image",
            field=models.ImageField(
                upload_to=core.helpers.upload_handle, verbose_name="圖片"
            ),
        ),
        migrations.AlterField(
            model_name="generalimage",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否啟用"),
        ),
        migrations.AlterField(
            model_name="generalimage",
            name="name",
            field=models.CharField(max_length=50, verbose_name="圖片名稱"),
        ),
    ]
