# Generated by Django 5.0.1 on 2024-11-17 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_generalimage_options_generalimage_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frontpageimage",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frontpage_images",
                to="products.productcategory",
                verbose_name="圖片分類",
            ),
        ),
        migrations.AlterField(
            model_name="generalimage",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_images",
                to="products.productcategory",
                verbose_name="圖片分類",
            ),
        ),
    ]
