# Generated by Django 5.0.1 on 2024-11-17 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_alter_generalimage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frontpageimage",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frontpage_images",
                to="products.productcategory",
                verbose_name="圖片分類",
            ),
        ),
    ]
