# Generated by Django 5.0.1 on 2024-11-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_alter_frontpageimage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frontpageimage",
            name="category",
            field=models.CharField(
                choices=[
                    ("carousel", "輪播圖片"),
                    ("banner", "橫幅圖片"),
                    ("thumbnail", "縮略圖"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=20,
                verbose_name="圖片分類",
            ),
        ),
    ]
