# Generated by Django 5.0.1 on 2024-11-18 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_alter_frontpageimage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationalproduct",
            name="product_option",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productoption",
            ),
            preserve_default=False,
        ),
    ]
