upstream uwsgi {
    # server unix:/web/shop/web.sock; # using a file socket
    server web:8000;  # using the docker network
}

server {
    listen 80;

    # 處理靜態文件
    location /static/ {
        alias /web/shop/staticfiles/;
    }

    location / {
        # using uwsgi protocal ↓↓↓ 
        uwsgi_pass uwsgi;
        include /etc/nginx/uwsgi_params; # the uwsgi_params file you installed
        # using uwsgi protocal ↑↑↑
        # using http protocal ↓↓↓ 
        # proxy_pass http://uwsgi;  # using http protocal
        # proxy_pass http://web:8000/;  # using http protocal
        # using uwsgi protocal ↑↑↑

    }

}